INSERT INTO fathers_quotes (author, quote) VALUES ('ملاك الرب للقديس أنطونيوس', 'اعمل هكذا فتخلص.');
INSERT INTO fathers_quotes (author, quote) VALUES ('صوت إلهي للقديس أنطونيوس', 'أنطونيوس اهتم بنفسك. إنها أحكام الله ولا تناسبك معرفتها.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس أنطونيوس الكبير', 'أينما ذهبت فليكن الله نصب عينيك، ومهما عملت فليكن لديك على عملك شاهد من الكتاب المقدس، وحيثما أقمت فلا تنتقل من مكانك بسهولة.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس أنطونيوس الكبير', 'العمل الكبير هو أن يعترف الإنسان بذنبه أمام الله ويتوقع التجربة حتى النفس الأخير.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس أنطونيوس الكبير', 'لا يستطيع أحد أن يدخل ملكوت السموات بدون التجارب.. إرفع التجارب فلا يخلص أحد.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس أنطونيوس الكبير', 'لا تثق ببرّك ولا تتحسر على ما عبر، واضبط لسانك وبطنك.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس أنطونيوس الكبير', 'رأيت فخاخ العدو منبثة في الأرض كلها.. المتواضعون هم من يسلمون منها.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس أنطونيوس الكبير', 'لقد أفنى البعض أجسادهم بالنسك ولكنهم، لعدم التمييز، ظلوا بعيدين عن الله.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس أنطونيوس الكبير', 'إن الحياة والموت يتعلقان بالقريب، فإننا إن ربحنا أخانا ربحنا الله، وإن أعثرناه أخطأنا إلى المسيح.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس أنطونيوس الكبير', 'لا أنا أرحمك ولا الله يرحمك ما دمت لا تقوم بنفسك بالتضرع إليه.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس أنطونيوس الكبير', 'أنا لا أخاف الله بعد الآن لأني أحبه، فإن المحبة تطرد الخوف.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس أنطونيوس الكبير', 'ضع مخافة الله نصب عينيك دائماً، تذكر ذاك الذي يميت ويحيي.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس أنطونيوس الكبير', 'أبغضوا العالم وكل ما في العالم، امقتوا كل راحة جسدية، ازهدوا في هذه الحياة لتحيوا لله.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس أنطونيوس الكبير', 'الطاعة والإمساك يخضعان الوحوش.');
INSERT INTO fathers_quotes (author, quote) VALUES ('الأنباأنطونيوس', 'أتعِب نفسك في قراءة الكتب المقدسة فهي تخلّصك من النجاسة.');
INSERT INTO fathers_quotes (author, quote) VALUES ('الأنباأنطونيوس', 'اختر التعب فهو يخلصك من جميع الشرور مع الصوم والصلاة والسهر.');
INSERT INTO fathers_quotes (author, quote) VALUES ('الأنباأنطونيوس', 'الإنسان الحر هو ذاك الذي لا تستعبده الملذات الجسدية بل يتحكم في الجسد بتمييز صالح وعفة.');
INSERT INTO fathers_quotes (author, quote) VALUES ('البابا شنودة الثالث', 'لا يجوز لنا أن نيأس من خلاص الخطاة، لأن قديسين كثيرين يعملون لأجلهم ويذكرونهم أمام الله في السماء.');
INSERT INTO fathers_quotes (author, quote) VALUES ('البابا شنودة الثالث', 'راجع نفسك كل يوم في أي شيء أخطأت فإذا صلبت من أجل خطاياك يغفرها لك الله.');
INSERT INTO fathers_quotes (author, quote) VALUES ('البابا شنودة الثالث', 'اذكر الموت فتزول من أمامك مغريات العالم.');
INSERT INTO fathers_quotes (author, quote) VALUES ('البابا شنودة الثالث', 'في كل مرة تخاف وبخ نفسك على قلة إيمانك.');
INSERT INTO fathers_quotes (author, quote) VALUES ('البابا شنودة الثالث', 'خذ نقطة الضعف التي فيك واجعلها موضوع صلواتك وجهادك خلال الصوم.');
INSERT INTO fathers_quotes (author, quote) VALUES ('البابا شنودة الثالث', 'الخدمة هي المدرس قبل أن تكون الدرس، هي حياة تنتقل من شخص إلى آخر.');
INSERT INTO fathers_quotes (author, quote) VALUES ('البابا شنودة الثالث', 'إن مريم العذراء قد عوضت سمعة حواء، أقامت توازناً لسمعة المرأة في العالم.');
INSERT INTO fathers_quotes (author, quote) VALUES ('البابا شنودة الثالث', 'الصلاة ليست مجرد طلب، إنما هي تأمل في جمال الله وصفاته المحيية للنفس.');
INSERT INTO fathers_quotes (author, quote) VALUES ('البابا شنودة الثالث', 'النفس القوية لا تقلق ولا تضطرب ولا تخاف ولا تنهار ولا تتردد.');
INSERT INTO fathers_quotes (author, quote) VALUES ('البابا شنودة الثالث', 'تكلم حينما تكون الأذن مستعدة لسماعك، وحبذا لو كانت مشتاقة إلي سماعك.');
INSERT INTO fathers_quotes (author, quote) VALUES ('البابا شنودة الثالث', 'الصمت ينفع أحياناً، ولكنه ليس قاعدة ثابتة، القاعدة الحكيمة هي أن يتكلم الإنسان حين يحسن الكلام ويصمت حين يحسن الصمت.');
INSERT INTO fathers_quotes (author, quote) VALUES ('البابا شنودة الثالث', 'الإنسان الروحي لا يستخدم ألفاظاً قاسية إنما رقيقة، لأن من ثمار الروح القدوس لطف.');
INSERT INTO fathers_quotes (author, quote) VALUES ('البابا شنودة الثالث', 'بدلاً من أن تلعنو الظلام أضيئوا شمعة.');
INSERT INTO fathers_quotes (author, quote) VALUES ('البابا شنودة الثالث', 'الإنسان المتواضع لا يقول كلمة تقلل من شأن أحد ولا يتصرف تصرفاً يخدش شعور أحد.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس أوغسطينوس', 'جلست على قمة العالم حينما أحسست في نفسي أنني لا أشتهي شيئاً ولا أخاف شيئاً.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس أوغسطينوس', 'النفس التي تعيش بالمحبة أكثر اتساعاً من السماء.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس أوغسطينوس', 'وأسفاه إنه من السهل أن نطلب أشياء من الله ولا نطلب الله نفسه، كأن العطية أفضل من العاطي.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس أوغسطينوس', 'احذر من اليأس من نفسك فقد أوصيت أن تتكل على الله لا على ذاتك.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس أوغسطينوس', 'لقد كنت معي ولكن أنا من أجل شقاوتي لم أكن معك يا الله.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس أوغسطينوس', 'لا تخف من تجارب إبليس، فالشيطان لا يستطيع أن ينصب فخاخه في الطريق لأن الطريق هو المسيح، لكنه ينصبها على جانبي الطريق.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس أوغسطينوس', 'ربي.. لست أدري ما تحمله لي الأيام لكن يكفيني ثقتي أنك معي تعتني بي وتحارب عني.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس أوغسطينوس', 'القلب الحاسد به دودة شريرة تنخر كل شيء فتحوله رماداً.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس أوغسطينوس', 'ستظل قلوبنا قلقة إلى أن تستريح فيك يا الله.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس أوغسطينوس', 'أتريد أن تصعد صلاتك إلى السماء؟ فامنحها جناحين وهما الصوم والصدقة.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس يوحنا ذهبي الفم', 'الله لا يلزم الذين لا يريدونه، لكنه يجتذب الذين يريدون.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس يوحنا ذهبي الفم', 'إن كنت في غاية الشيب وأخطأت فأدخل إلى الكنيسة واندم، لأن هذا المكان هو مستشفى وليس محكمة.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس يوحنا ذهبي الفم', 'لا نقدر أن نجري في طريق الله إلا محمولين على أجنحة الروح.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس يوحنا ذهبي الفم', 'احمل الصليب حينما تحارب الشيطان، ليس فقط بأن ترسمه عليك بل أيضاً تحمل من هو معلق على الصليب.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس يوحنا ذهبي الفم', 'أن الدموع التي نذرفها على الخطايا أثمن من كل جواهر العالم.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس يوحنا ذهبي الفم', 'قال الشيطان للرب أترك لي الأقوياء فإني كفيل بهم، أما الضعفاء فلا أقدر عليهم لأنهم يحاربوني بقوتك.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس يوحنا ذهبي الفم', 'ولد من امرأة لكي تصير أنت ابناً لله.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس باسيليوس الكبير', 'الصوم الحقيقي هو سجن الرذائل أي ضبط اللسان وإمساك الغضب وقهر الشهوات.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس باسيليوس الكبير', 'ابتعد عن نظر وسماع ما لا يفيد فتتخلص من فعل ما لا يفيد.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس باسيليوس الكبير', 'جيد ألا تخطئ، وإن أخطأت فجيد ألا تؤخر التوبة، وإن تبت فجيد ألا تعاود الخطيئة.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس باسيليوس الكبير', 'يجب أن نصوم لنرجع إلى الفردوس السمائي، لأن الصوم يرد إلينا الخسائر المسببة عن عدم صوم آدم.');
INSERT INTO fathers_quotes (author, quote) VALUES ('مار إسحق السرياني', 'ضبط الحواس يقلع الخطايا وحفظ القلب يقطع الآلام التي تلد الخطايا.');
INSERT INTO fathers_quotes (author, quote) VALUES ('مار إسحق السرياني', 'الاتضاع هو أن يحقر الإنسان ذاته في كل شيء.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس إسحق السرياني', 'صوم اللسان خير من صوم الفم، وصوم القلب أخير من الاثنين.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس مار إسحق', 'كل جهاد ضد الخطية وشهواتها يجب أن يبتدئ بالصوم.');
INSERT INTO fathers_quotes (author, quote) VALUES ('مار إسحق السرياني', 'ما دمت لك عينان فاملآهما بالدموع قبل أن تغطى بالتراب.');
INSERT INTO fathers_quotes (author, quote) VALUES ('مار إسحق السرياني', 'طوبى للباكين من أجل الحق، لأنه من خلال دموعهم يرون باستمرار وجه الله.');
INSERT INTO fathers_quotes (author, quote) VALUES ('أبونا بيشوي كامل', 'إن الذي لا يكرم الأم العذراء فهو يسئ إلى ابنها.');
INSERT INTO fathers_quotes (author, quote) VALUES ('أبونا بيشوي كامل', 'سيظل يسوع فاتحاً ذراعيه باستمرار لأنه يريد نفسي التي مات عنها لكي يحتضنها.');
INSERT INTO fathers_quotes (author, quote) VALUES ('أبونا بيشوي كامل', 'التوبة للنفس كمخاض المرأة، ولكن نصيبها رؤية المسيح كما ترى المرأة طفلها مولوداً.');
INSERT INTO fathers_quotes (author, quote) VALUES ('أبونا بيشوي كامل', 'الإنسان المسيحي إنسان يجدد ذهنه دائماً بالتوبة وليس حياته.');
INSERT INTO fathers_quotes (author, quote) VALUES ('أبونا بيشوي كامل', 'في اللحظة التي يسقط فيها الإنسان في نقد الآخرين، في اللحظة عينها تهرب منه التوبة.');
INSERT INTO fathers_quotes (author, quote) VALUES ('أبونا بيشوي كامل', 'اعتراف بلا توبة لا قيمة له.');
INSERT INTO fathers_quotes (author, quote) VALUES ('أبونا بيشوي كامل', 'الصلاة هي الطريق الوحيد لفهم إرادة الله.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس إغناطيوس الثيئوفوروس', 'لابد لي أن أُطحَن بأنياب الوحوش لأصبح خبزاً جيداً على مائدة المسيح.');
INSERT INTO fathers_quotes (author, quote) VALUES ('الأنبا موسى الأسود', 'لا تكن قاسي القلب على أخيك فأننا جميعاً قد تغلبنا الأفكار الشريرة.');
INSERT INTO fathers_quotes (author, quote) VALUES ('البابا كيرلس السادس', 'أذهب واصطلح مع من أساء إليك قبل أن يأتي هو ويعتذر إليك فيسرق إكليلك.');
INSERT INTO fathers_quotes (author, quote) VALUES ('البابا كيرلس السادس', 'كن مطمئناً جداً جداً ولا تفكر في الأمر كثيراً، بل دع الأمر لمن بيده الأمر.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديسة سارة الراهبة', 'لا تضع رجلي على السلّم إلا أن أتصوّر أنني أموت قبل أن أرفعها.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس يوحنا الدرجي', 'الحكيم يتأمل فضائل غيره ليقتنيها لنفسه والجاهل يتأمل رذائل غيره ويدينه عليها.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديسة ثيئودورا', 'لا النسك ولا السهر ولا أي تعب يقدر أن يخلّص الإنسان سوى الاتضاع الحقيقي.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس أنطونيوس الكبير', 'أينما ذهبت فليكن الله نصب عينيك.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس أنطونيوس الكبير', 'مهما عملت فليكن لديك على عملك شاهد من الكتاب المقدس.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس أنطونيوس الكبير', 'حيثما أقمت فلا تنتقل من مكانك بسهولة.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس أنطونيوس الكبير', 'كما أن السمك إن بقي مدة خارج الماء يموت، كذلك الرهبان إن تأخروا عن قلاليهم بددوا قوة السكينة فيهم.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس أنطونيوس الكبير', 'من يعتزل في البرية ينعتق من حروب ثلاث هي السمع والكلام والنظر.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس أنطونيوس الكبير', 'الرجل العاقل يشبه مركبأ محملاً بالخيرات، لكن المهم أن يصل إلى الميناء.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس أنطونيوس الكبير', 'انك تشبه قرية واجهتها جميلة مزدانة لكنها من داخل نهبى اللصوص.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس أنطونيوس الكبير', 'من يضرب كتلة من حديد يتبصّرقبلاً في ما ينوي عمله: أمنجلا أم سيفاً أم فأساً.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس أنطونيوس الكبير', 'على الراهب أن يطلع الشيوخ على عدد الخطوات التي يخطوها وقطرات الماء التي يشربها.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس أنطونيوس الكبير', 'لا تكن قليل السمع لكلمة الرب لئلا تكون وعاء لجميع الشرور.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس أوغسطينوس', 'أتريد أن تعرف نوع الحب الذي فيك؟ أنظر أين يقودك.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس أوغسطينوس', 'أحبب أعدائك، لئلا تبغض عن جهل أصدقائك.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس أوغسطينوس', 'أغفر للآخرين خطاياهم، وصلي من أجل خطاياك.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس أوغسطينوس', 'إن العهد القديم مكشوف في الجديد، والعهد الجديد مخبوء في القديم.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس أوغسطينوس', 'إن أردت أن تكون أفضل، فاسع إلى ماهو أرفع منك.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس أوغسطينوس', 'إن حاجتك في الصلاة إلى تقوى لا إلى ثرثرة.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس أوغسطينوس', 'إن رضيت عن نفسك، صار الله غير راض عنك.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس أوغسطينوس', 'إن صمت لسانك فلتكن من القلب صلاتك.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس أوغسطينوس', 'تقرأ فيتحدث الله إليك، وتصلي فتتحدث أنت إليه.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس أوغسطينوس', 'يا طماع لما تتوق إلى السماء والأرض؟ أليس خالقهما أفضل منهما؟');
INSERT INTO fathers_quotes (author, quote) VALUES ('مار إفرام السرياني', 'قد خبأت كنوزا كثيرة في كلمتك حتى أن كلا منا يصير غنيا بقدر تأمله فيها.');
INSERT INTO fathers_quotes (author, quote) VALUES ('مار إفرام السرياني', 'أنا يا رب إناء ترابي فارغ، إملأني كما ملأت أجران الماء من الحياة.');
INSERT INTO fathers_quotes (author, quote) VALUES ('مار إفرام السرياني', 'الصلاة هي أم الفضائل، وتبطل الغضب وتوبخ عليه.');
INSERT INTO fathers_quotes (author, quote) VALUES ('مار إفرام السرياني', 'بالشجرة التي قتلنا بها الشيطان (شجرة المعرفة)، أنقذنا الرب (شجرة الصليب).');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس أفرام السرياني', 'ثمين هو الصوم الطاهر أمام الله، وهو محفوظ ككنز في السماء.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس أفرام السرياني', 'خبز وملح مع سكوت وراحة، أفضل من أطعمة شريفة مع هموم وأحزان.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس مار إفرام', 'إجعل اليوم يوم توبتك لئلا يأتيك الموت في هذه الليلة.');
INSERT INTO fathers_quotes (author, quote) VALUES ('مار إفرام السرياني', 'اليوم الذي لا تجلس فيه ساعة مع نفسك لا تحسبه من عداد أيام حياتك.');
INSERT INTO fathers_quotes (author, quote) VALUES ('مار إفرام السرياني', 'ما دمت تنظر غيرك فلن ترى نفسك.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس مكاريوس الكبير', 'كما أن بستاناً واحداً يستقى من ينبوع واحد تنمو فيه أثمار مختلفة، كذلك الرهبان يشربون من روح واحد وثمرهم مختلف.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس مكاريوس الكبير', 'كونوا أبناء السلام ليحل سلام الرب عليكم.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس مكاريوس الكبير', 'كونوا بني الطاعة لتنجوا من الشيطان.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس مكاريوس الكبير', 'القلب النقى ينظر كل الناس أنقياء.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس مكاريوس الكبير', 'لا غلبة بدون قتال ولا اكليل بدون غلبة.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس مكاريوس الكبير', 'الباب ضيق والطريق كربة، ولكن المدينة مملوءة فرحاً وسروراً.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس يوحنا السلمي', 'فوض إلى ربك ضعف طبيعتك تنل دون أن تدري موهبة العفة.');
INSERT INTO fathers_quotes (author, quote) VALUES ('الأب يوحنا السلمي', 'الحب هو قبل كل شيء دحض كل فكر عداوة.');
INSERT INTO fathers_quotes (author, quote) VALUES ('البابا شنودة الثالث', 'تكلم حينما تكون الأذن مستعدة لسماعك، وحبذا لو كانت مشتاقة إلي سماعك.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس يوحنا التبايسي', 'الصوم الجسدي هو الجوع من الغذاء، وصوم النفس هو أن يجوع الإنسان ويعطش للبر.');
INSERT INTO fathers_quotes (author, quote) VALUES ('من بستان الرهبان', 'إن إمساك البطن هو أن تقلل من شبعك قليلاً.');
INSERT INTO fathers_quotes (author, quote) VALUES ('من بستان الرهبان', 'من يضبط فمه فإن أفكاره تموت كجرّة فيها حيات وعقارب إذا سُدّ فمها.');
INSERT INTO fathers_quotes (author, quote) VALUES ('الأب يوحنا القصير', 'إذا أراد ملكٌ أن يأخذَ مدينةَ الأعداءِ فإنه يقطعُ عنها الشرابَ والطعامَ لتذل، هكذا أوجاع الجسد تضعف بالجوع.');
INSERT INTO fathers_quotes (author, quote) VALUES ('الأب يوحنا القصير', 'ابتداء التدبير الجيد هو أن يبتعدَ الإنسانُ عن كلِّ شيءٍ يُشغلُ العقلَ.');
INSERT INTO fathers_quotes (author, quote) VALUES ('الأنباأنطونيوس', 'كل ما يبعدك عن الله لا تفعله، ولتكن نفسك كائنة مع الله في كل وقت.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس أنطونيوس الكبير', 'أينما ذهبت فليكن الله نصب عينيك.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس أنطونيوس الكبير', 'مهما عملت فليكن لديك على عملك شاهد من الكتاب المقدس.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس أنطونيوس الكبير', 'حيثما أقمت فلا تنتقل من مكانك بسهولة.');
INSERT INTO fathers_quotes (author, quote) VALUES ('الأنباأنطونيوس', 'العمل الكبير هو أن يعترف الإنسان بذنبه أمام الله ويتوقع التجربة حتى النفس الأخير.');
INSERT INTO fathers_quotes (author, quote) VALUES ('الأنباأنطونيوس', 'لا يستطيع أحد أن يدخل ملكوت السموات بدون التجارب.');
INSERT INTO fathers_quotes (author, quote) VALUES ('الأنباأنطونيوس', 'إرفع التجارب فلا يخلص أحد.');
INSERT INTO fathers_quotes (author, quote) VALUES ('الأنباأنطونيوس', 'لا تثق ببرّك ولا تتحسر على ما عبر، واضبط لسانك وبطنك.');
INSERT INTO fathers_quotes (author, quote) VALUES ('الأنباأنطونيوس', 'رأيت فخاخ العدو منبثة في الأرض كلها.. المتواضعون هم من يسلمون منها.');
INSERT INTO fathers_quotes (author, quote) VALUES ('الأنباأنطونيوس', 'لا أنا أرحمك ولا الله يرحمك ما دمت لا تقوم بنفسك بالتضرع إليه.');
INSERT INTO fathers_quotes (author, quote) VALUES ('الأنباأنطونيوس', 'الطاعة والإمساك يخضعان الوحوش.');
INSERT INTO fathers_quotes (author, quote) VALUES ('الأنباأنطونيوس', 'أتعِب نفسك في قراءة الكتب المقدسة فهي تخلصك من النجاسة.');
INSERT INTO fathers_quotes (author, quote) VALUES ('الأنباأنطونيوس', 'أبغضوا العالم وكل ما في العالم، امقتوا كل راحة جسدية، ازهدوا في هذه الحياة لتحيوا لله.');
INSERT INTO fathers_quotes (author, quote) VALUES ('الأنباأنطونيوس', 'تذكر ذاك الذي يميت ويحيي.');
INSERT INTO fathers_quotes (author, quote) VALUES ('الأنباأنطونيوس', 'نوحوا وابكوا وتنهدوا من قلوبكم.');
INSERT INTO fathers_quotes (author, quote) VALUES ('الأنباأنطونيوس', 'تهاونوا بأجسادكم لتخلصوا نفوسكم.');
INSERT INTO fathers_quotes (author, quote) VALUES ('الأنباأنطونيوس', 'على الراهب أن يطلع الشيوخ على عدد الخطوات التي يخطوها وقطرات الماء التي يشربها.');
INSERT INTO fathers_quotes (author, quote) VALUES ('الأنباأنطونيوس', 'الزم الحزن على خطاياك كمثل من عنده ميت.');
INSERT INTO fathers_quotes (author, quote) VALUES ('الأنباأنطونيوس', 'أوقد سراجك بدموع عينيك.');
INSERT INTO fathers_quotes (author, quote) VALUES ('الأنباأنطونيوس', 'لا تكن مقاتلاً باللسان، واجعل كل أحد يباركك.');
INSERT INTO fathers_quotes (author, quote) VALUES ('الأنباأنطونيوس', 'كما أن السمك إذا خرج من الماء يموت، كذلك الراهب إذا خرج من قلايته يموت خوف الله من قلبه.');
INSERT INTO fathers_quotes (author, quote) VALUES ('الأنباأنطونيوس', 'لا تأكل حتى تشبع ولا تنم إلا يسيراً بقدر.');
INSERT INTO fathers_quotes (author, quote) VALUES ('الأنباأنطونيوس', 'إياك والكذب فهو يطرد مخافة الله من الإنسان.');
INSERT INTO fathers_quotes (author, quote) VALUES ('الأنباأنطونيوس', 'لا تكن قليل السمع لكلمة الرب لئلا تكون وعاء لجميع الشرور.');
INSERT INTO fathers_quotes (author, quote) VALUES ('الأنباأنطونيوس', 'كل ما يبعدك عن الله لا تفعله، ولتكن نفسك كائنة مع الله في كل وقت.');
INSERT INTO fathers_quotes (author, quote) VALUES ('مار إسحق السرياني', 'أعطني قلباً منسحقاً وقوة لكي ينبع من عيني دموع مقبولة فيضئ قلبي بالصلاة النقية.');
INSERT INTO fathers_quotes (author, quote) VALUES ('مار إسحق السرياني', 'الصلاة هي طيران عقلنا إلى الله.');
INSERT INTO fathers_quotes (author, quote) VALUES ('مار إسحق السرياني', 'صلاة لحقود كبذار ألقيت على الصخر.');
INSERT INTO fathers_quotes (author, quote) VALUES ('مار إسحق السرياني', 'مبدأ التوبة هو الإتضاع الذي بلا زي كاذب مشوش.');
INSERT INTO fathers_quotes (author, quote) VALUES ('مار إسحق السرياني', 'التوبة هي باب الرحمة المفتوح لطالبيه.');
INSERT INTO fathers_quotes (author, quote) VALUES ('مار إسحق السرياني', 'لا فضيلة قبل التوبة.');
INSERT INTO fathers_quotes (author, quote) VALUES ('مار إسحق السرياني', 'من يعرف خطاياه لهو أعظم ممن يقيم موتى.');
INSERT INTO fathers_quotes (author, quote) VALUES ('مار إسحق السرياني', 'لا خطية بلا مغفرة إلا التي بلا توبة.');
INSERT INTO fathers_quotes (author, quote) VALUES ('مار إسحق السرياني', 'إن اصطلحت مع ذاتك تصطلح معك السماء والأرض.');
INSERT INTO fathers_quotes (author, quote) VALUES ('مار إسحق السرياني', 'الجسد عين ناظرة إلى الأرض أما المحبة عين ناظرة إلى السماء.');
INSERT INTO fathers_quotes (author, quote) VALUES ('مار إسحق السرياني', 'يستحيل أن يترك الله قلباً منسحقاً بدون عزاء.');
INSERT INTO fathers_quotes (author, quote) VALUES ('مار إسحق السرياني', 'رفض الكرامة يجعل الإنسان مكرماً.');
INSERT INTO fathers_quotes (author, quote) VALUES ('مار إسحق السرياني', 'مخافة الله هي بدء الفضيلة وهي بنت الإيمان.');
INSERT INTO fathers_quotes (author, quote) VALUES ('مار إسحق السرياني', 'المتضع في القلب متضع في الجسد.');
INSERT INTO fathers_quotes (author, quote) VALUES ('مار إسحق السرياني', 'المعرفة الحقيقية هي ينبوع الاتضاع.');
INSERT INTO fathers_quotes (author, quote) VALUES ('مار إسحق السرياني', 'ما هي النقاوة؟ إنها قلب رحوم لكل الخليقة.');
INSERT INTO fathers_quotes (author, quote) VALUES ('مار إسحق السرياني', 'أحب الاتضاع في كل تدبيرك لتخلص من القخاخ التي لا تدرك.');
INSERT INTO fathers_quotes (author, quote) VALUES ('مار إسحق السرياني', 'المكافأة ليست للعمل تعطى بل للاتضاع.');
INSERT INTO fathers_quotes (author, quote) VALUES ('مار إسحق السرياني', 'الاتضاع يتقدم النعمة، والعظمة تتقدم التأديب.');
INSERT INTO fathers_quotes (author, quote) VALUES ('مار إسحق السرياني', 'كما أن الملح يصلح لجميع المآكل هكذا هو الإتضاع لكل الفضائل.');
INSERT INTO fathers_quotes (author, quote) VALUES ('مار إسحق السرياني', 'فكر الكسلان معمل للشيطان.');
INSERT INTO fathers_quotes (author, quote) VALUES ('مار إسحق السرياني', 'لا تكره الشدائد فباحتمالها تنال الكرامة وبها تقترب إلى الله.');
INSERT INTO fathers_quotes (author, quote) VALUES ('مار إسحق السرياني', 'طوبى للباكين من أجل الحق، لأنهم من خلال دموعهم يرون باستمرار وجه الله.');
INSERT INTO fathers_quotes (author, quote) VALUES ('مار إسحق السرياني', 'فم يشكر دائماً يقبل البركة من الله.');
INSERT INTO fathers_quotes (author, quote) VALUES ('مار إسحق السرياني', 'المدافع عن المظلوم يجد الله ناصراً محبوباً عنه.');
INSERT INTO fathers_quotes (author, quote) VALUES ('مار إسحق السرياني', 'من لم يخضع جسده لا يخضع له عقله.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس مكاريوس الكبير', 'القلب النقى ينظر كل الناس أنقياء.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس مكاريوس الكبير', 'لا غلبة بدون قتال ولا اكليل بدون غلبة.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس مكاريوس الكبير', 'الباب ضيق والطريق كربة، ولكن المدينة مملوءة فرحاً وسروراً.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس مكاريوس الكبير', 'كونوا أبناء السلام ليحل سلام الرب عليكم.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس مكاريوس الكبير', 'اغفروا لبعضكم بعضاً لتنالوا الغفران.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس مكاريوس الكبير', 'الصوم هو سبب الغلبة والنصرة.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس مكاريوس الكبير', 'صوموا مع المخلص لتتمجدوا معه وتغلبوا الشيطان.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس مكاريوس الكبير', 'لا تهاونوا لئلا تكون الطلبة من أجلكم باطلة.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس مكاريوس الكبير', 'اصبروا للتجارب التي تأتي عليكم من العدو فإن الله يعينكم.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس مكاريوس الكبير', 'عمل الصلاح عسير وشاق ولكنه ينجي من النار.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس مكاريوس الكبير', 'إذا أخطأ إنسان وندم وأقر بخطئه، فهو أفضل من الرجل الذي يعمل الصالح ويزكي نفسه.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس مكاريوس الكبير', 'نفس الكامل في الفضائل نجدها نقية كالشمس.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس مكاريوس الكبير', 'إن نحن ذكرنا السيئات التي تحل بنا من الناس، فإننا نقطع قوة ذكر الله من قلوبنا.');
INSERT INTO fathers_quotes (author, quote) VALUES ('البابا شنودة الثالث', 'لا يجوز لنا أن نيأس من خلاص الخطاة، لأن قديسين كثيرين يعملون لأجلهم ويذكرونهم أمام الله في السماء.');
INSERT INTO fathers_quotes (author, quote) VALUES ('البابا شنودة الثالث', 'اذكر الموت فتزول من أمامك مغريات العالم.');
INSERT INTO fathers_quotes (author, quote) VALUES ('البابا شنودة الثالث', 'في كل مرة تخاف وبخ نفسك على قلة إيمانك.');
INSERT INTO fathers_quotes (author, quote) VALUES ('البابا شنودة الثالث', 'خذ نقطة الضعف التي فيك واجعلها موضوع صلواتك وجهادك خلال الصوم.');
INSERT INTO fathers_quotes (author, quote) VALUES ('البابا شنودة الثالث', 'الخدمة هي المدرس قبل أن تكون الدرس، هي حياة تنتقل من شخص إلى آخر.');
INSERT INTO fathers_quotes (author, quote) VALUES ('البابا شنودة الثالث', 'إن مريم العذراء قد عوضت سمعة حواء وأقامت توازناً لسمعة المرأة في العالم.');
INSERT INTO fathers_quotes (author, quote) VALUES ('البابا شنودة الثالث', 'الصلاة ليست مجرد طلب، إنما هي تأمل في جمال الله وصفاته المحيية للنفس.');
INSERT INTO fathers_quotes (author, quote) VALUES ('البابا شنودة الثالث', 'كل فضيلة خالية من الحب لا تحسب فضيلة.');
INSERT INTO fathers_quotes (author, quote) VALUES ('البابا شنودة الثالث', 'بدلا من أن تلعنوا الظلام أضيئوا شمعه.');
INSERT INTO fathers_quotes (author, quote) VALUES ('البابا شنودة الثالث', 'الإنسان المتواضع لا يقول كلمة تقلل من شأن أحد ولا يتصرف تصرفاً يخدش شعور أحد.');
INSERT INTO fathers_quotes (author, quote) VALUES ('البابا شنودة الثالث', 'لك نفس واحدة إن ربحتها ربحت كل شيء وإن خسرتها خسرت كل شيء.');
INSERT INTO fathers_quotes (author, quote) VALUES ('البابا شنودة الثالث', 'الضمير هو صوت وضعه الله في الإنسان يدعوه إلى الخير ويبكته على الشر ولكنه ليس صوت الله.');
INSERT INTO fathers_quotes (author, quote) VALUES ('البابا شنودة الثالث', 'أخلى الله ذاته وأخذ صورة العبد لكي يعطي درساً للعبد الذي أراد أن يرفع ذاته ويصير إلهاً.');
INSERT INTO fathers_quotes (author, quote) VALUES ('البابا شنودة الثالث', 'النفس القوية لا تقلق ولا تضطرب ولا تخاف ولا تنهار ولا تتردد.');
INSERT INTO fathers_quotes (author, quote) VALUES ('البابا شنودة الثالث', 'تكلم حينما تكون الأذن مستعدة لسماعك، وحبذا لو كانت مشتاقة إلي سماعك.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس أوغسطينوس', 'جلست على قمة العالم حينما أحسست في نفسي أنني لا أشتهي شيئاً ولا أخاف شيئاً.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس أوغسطينوس', 'النفس التي تعيش بالمحبة أكثر اتساعاً من السماء.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس أوغسطينوس', 'وأسفاه إنه من السهل أن نطلب أشياء من الله ولا نطلب الله نفسه، كأن العطية أفضل من العاطي.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس أوغسطينوس', 'احذر من اليأس من نفسك فقد أوصيت أن تتكل على الله لا على ذاتك.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس أوغسطينوس', 'لقد كنت معي ولكن أنا من أجل شقاوتي لم أكن معك يا الله.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس أوغسطينوس', 'لا تخف من تجارب إبليس، فالشيطان لا يستطيع أن ينصب فخاخه في الطريق لأن الطريق هو المسيح.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس أوغسطينوس', 'ربي.. لست أدري ما تحمله لي الأيام لكن يكفيني ثقتي أنك معي تعتني بي وتحارب عني.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس أوغسطينوس', 'القلب الحاسد به دودة شريرة تنخر كل شيء فتحوله رماداً.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس أوغسطينوس', 'ستظل قلوبنا قلقة إلى أن تستريح فيك يا الله.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس أوغسطينوس', 'أتريد أن تصعد صلاتك إلى السماء؟ فامنحها جناحين وهما الصوم والصدقة.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس أوغسطينوس', 'أتريد أن تعرف نوع الحب الذي فيك؟ انظر أين يقودك.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس يوحنا ذهبي الفم', 'الله لا يلزم الذين لا يريدونه، لكنه يجتذب الذين يريدون.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس يوحنا ذهبي الفم', 'إن كنت في غاية الشيب وأخطأت فأدخل إلى الكنيسة واندم، لأن هذا المكان هو مستشفى وليس محكمة.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس يوحنا ذهبي الفم', 'لا نقدر أن نجري في طريق الله إلا محمولين على أجنحة الروح.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس يوحنا ذهبي الفم', 'احمل الصليب حينما تحارب الشيطان، ليس فقط بأن ترسمه عليك بل أيضاً تحمل من هو معلق على الصليب.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس يوحنا ذهبي الفم', 'أن الدموع التي نذرفها على الخطايا أثمن من كل جواهر العالم.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس يوحنا ذهبي الفم', 'قال الشيطان للرب أترك لي الأقوياء فإني كفيل بهم، أما الضعفاء فلا أقدر عليهم لأنهم يحاربوني بقوتك.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس يوحنا ذهبي الفم', 'إن أردت أن لا يتأتى لك الحزن فلا تحزن إنساناً ما.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس يوحنا ذهبي الفم', 'السكون هو كمال الفلسفة، فمن يعيش بالسكون فإنه يستطيع أن يتمسك بجميع الحسنات.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس يوحنا ذهبي الفم', 'ولد من امرأة لكي تصير أنت ابناً لله.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس أفرام السرياني', 'خبز وملح مع سكوت وراحة، أفضل من أطعمة شريفة مع هموم وأحزان.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس أفرام السرياني', 'ثمين هو الصوم الطاهر أمام الله، وهو محفوظ ككنز في السماء.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس أفرام السرياني', 'الصلاة هي أم الفضائل، وتبطل الغضب وتوبخ عليه.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس أفرام السرياني', 'بالشجرة التي قتلنا بها الشيطان، أنقذنا الرب.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس أفرام السرياني', 'أنا يا رب إناء ترابي فارغ، إملأني كما ملأت أجران الماء من الحياة.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس أفرام السرياني', 'إجعل اليوم يوم توبتك لئلا يأتيك الموت في هذه الليلة.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس مار إفرام', 'اليوم الذي لا تجلس فيه ساعة مع نفسك لا تحسبه من عداد أيام حياتك.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس مار إفرام', 'اليوم هو لك أما الغد فلست تدري لمن يكون.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس مار إفرام', 'ما دمت تنظر غيرك فلن ترى نفسك.');
INSERT INTO fathers_quotes (author, quote) VALUES ('الأنبا موسى الأسود', 'لا تكن قاسي القلب على أخيك فإننا جميعاً قد تغلبنا الأفكار الشريرة.');
INSERT INTO fathers_quotes (author, quote) VALUES ('الأنبا موسى الأسود', 'أربعة أمور تحفظ الشباب من الفكر الردئ: القراءة في الكتب المقدسة، طرح الكسل، القيام في الليل للصلاة، التحلي بالتواضع دائماً.');
INSERT INTO fathers_quotes (author, quote) VALUES ('الأنبا موسى الأسود', 'من يحتمل ظلماً من أجل الرب يعتبر شهيداً.');
INSERT INTO fathers_quotes (author, quote) VALUES ('الأنبا موسى الأسود', 'سكوت اللسان يطرد الأفكار، وكثرة الكلام تلد الضجر والهوس.');
INSERT INTO fathers_quotes (author, quote) VALUES ('الأنبا موسى الأسود', 'خوف الله يطرد جميع الرذائل والضجر يطرد خوف الله.');
INSERT INTO fathers_quotes (author, quote) VALUES ('الأنبا موسى الأسود', 'إياك والبطالة لئلا تحزن، أحرى بك أن تعمل بيديك لأن البطالة موت وسقطة للنفس.');
INSERT INTO fathers_quotes (author, quote) VALUES ('الأنبا موسى الأسود', 'قهر الشهوة يدل على تمام الفضيلة والإنهزام لها يدل على نقص المعرفة.');
INSERT INTO fathers_quotes (author, quote) VALUES ('الأنبا موسى الأسود', 'أربعة مصدر ظلمة العقل: مقت الرفيق، الإزدراء به، حسده، سوء الظن به.');
INSERT INTO fathers_quotes (author, quote) VALUES ('أبونا بيشوي كامل', 'إن الذي لا يكرم الأم العذراء فهو يسئ إلى ابنها.');
INSERT INTO fathers_quotes (author, quote) VALUES ('أبونا بيشوي كامل', 'سيظل يسوع فاتحاً ذراعيه باستمرار لأنه يريد نفسي التي مات عنها لكي يحتضنها.');
INSERT INTO fathers_quotes (author, quote) VALUES ('أبونا بيشوي كامل', 'أولاد الله يعيشون غربتهم في العالم وأنظارهم متجهة للسماء.');
INSERT INTO fathers_quotes (author, quote) VALUES ('أبونا بيشوي كامل', 'من يعاتبك ويوبخك على زلاتك أحبه مثل نفسك واتخذه لك صديقاً.');
INSERT INTO fathers_quotes (author, quote) VALUES ('أبونا بيشوي كامل', 'الصلاة هي الطريق الوحيد لفهم إرادة الله.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس باسيليوس الكبير', 'الصوم الحقيقي هو سجن الرذائل أي ضبط اللسان وإمساك الغضب وقهر الشهوات.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس باسيليوس الكبير', 'ابتعد عن نظر وسماع ما لا يفيد فتتخلص من فعل ما لا يفيد.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس باسيليوس الكبير', 'جيد ألا تخطئ، وإن أخطأت فجيد ألا تؤخر التوبة، وإن تبت فجيد ألا تعاود الخطيئة.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس باسيليوس الكبير', 'علامة التكبر قنوع الإنسان برأي نفسه.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس باسيليوس الكبير', 'درب جسدك على طاعة نفسك، ودرب نفسك على طاعة الله.');
INSERT INTO fathers_quotes (author, quote) VALUES ('الأنبا يوحنا القصير', 'إذا أراد ملك أن يأخذ مدينة الأعداء فإنه يقطع عنها الشراب والطعام لتذل، هكذا أوجاع الجسد تضعف بالجوع.');
INSERT INTO fathers_quotes (author, quote) VALUES ('الأنبا يوحنا القصير', 'ابتداء التدبير الجيد هو أن يبتعد الإنسان عن كل شيء يشغل العقل.');
INSERT INTO fathers_quotes (author, quote) VALUES ('الأنبا يوحنا القصير', 'يجب قبل كل شيء أن نقوّم التواضع لأن هذه الوصية هي الأولى.');
INSERT INTO fathers_quotes (author, quote) VALUES ('الأنبا يوحنا القصير', 'السكون أفضل من جميع الأعمال لأنه بدوامه تهدأ الأفكار وتموت المشيئة.');
INSERT INTO fathers_quotes (author, quote) VALUES ('الأنبا يوحنا القصير', 'نفس الراهب العاجز تصير مأوى لكل شر.');
INSERT INTO fathers_quotes (author, quote) VALUES ('الأنبا يوحنا القصير', 'الراهب لا تفيده القراءة والصلوات ما لم يكن متواضعاً محباً للفقراء والمساكين.');
INSERT INTO fathers_quotes (author, quote) VALUES ('الشيخ الروحاني', 'قلب المحب هو عرش سكنه الروح القدس ويحل فيه الثالوث الأقدس.');
INSERT INTO fathers_quotes (author, quote) VALUES ('الشيخ الروحاني', 'من يترحم على إنسان، فإن باب الرب مفتوح لطلباته في كل ساعة.');
INSERT INTO fathers_quotes (author, quote) VALUES ('الشيخ الروحاني', 'ذو الإفراز بكسرة خبز يشتري لنفسه الملكوت.');
INSERT INTO fathers_quotes (author, quote) VALUES ('الشيخ الروحاني', 'من يفرح بحسنات كل الناس، تفيض عليه الحسنات من الرب.');
INSERT INTO fathers_quotes (author, quote) VALUES ('الشيخ الروحاني', 'فم الساكت يترجم أسرار الله.');
INSERT INTO fathers_quotes (author, quote) VALUES ('الشيخ الروحاني', 'أفضل لك أن تجعل في بطنك جمر نار، ولا أطبخة الرؤساء.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس برصنوفيوس', 'وجع القلب يجلب الطهارة، والطهارة تلد سكوت القلب.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس برصنوفيوس', 'غرباء نحن، فلنكن غرباء بالكمال، ولا نحسب أنفسنا شيئاً.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس برصنوفيوس', 'إذا مت عن كل إنسان، صيرك ذلك متحداً بالله.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس برصنوفيوس', 'إذا نحن اتضعنا فإن الرب يطرد عنا الشيطان.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس برصنوفيوس', 'أن نغلق باب فمنا أفضل من أن نغلق باب قلايتنا.');
INSERT INTO fathers_quotes (author, quote) VALUES ('الأنبا باخوميوس', 'الرهبنة هي الصوم بمقدار، والصلاة بمداومة، وعفة الجسد وطهارة القلب.');
INSERT INTO fathers_quotes (author, quote) VALUES ('الأنبا باخوميوس', 'اسلك طريق الاتضاع لأن الله لا يرد المتواضع خائباً.');
INSERT INTO fathers_quotes (author, quote) VALUES ('الأنبا باخوميوس', 'احذر من تكبر القلب لأنه أشنع الرذائل كلها.');
INSERT INTO fathers_quotes (author, quote) VALUES ('الأنبا باخوميوس', 'كن وديعاً ليحكمك الرب ويمألك معرفة وفهماً.');
INSERT INTO fathers_quotes (author, quote) VALUES ('الأنبا باخوميوس', 'إياك والنجاسة فهي تفصل الإنسان عن الله.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس إغناطيوس الثيئوفوروس', 'لابد لي أن أُطحَن بأنياب الوحوش لأصبح خبزاً جيداً على مائدة المسيح.');
INSERT INTO fathers_quotes (author, quote) VALUES ('البابا كيرلس السادس', 'كن مطمئناً جداً جداً ولا تفكر في الأمر كثيراً، بل دع الأمر لمن بيده الأمر.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديسة سارة الراهبة', 'لا تضع رجلي على السلّم إلا أن أتصوّر أنني أموت قبل أن أرفعها.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديس يوحنا الدرجي', 'الحكيم يتأمل فضائل غيره ليقتنيها لنفسه والجاهل يتأمل رذائل غيره ويدينه عليها.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديسة ثيئودورا', 'لا النسك ولا السهر ولا أي تعب يقدر أن يخلص الإنسان سوى الاتضاع الحقيقي.');
INSERT INTO fathers_quotes (author, quote) VALUES ('البابا كيرلس السادس', 'أذهب واصطلح مع من أساء إليك قبل أن يأتي هو ويعتذر إليك فيسرق إكليلك.');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديسين', 'سأتوب الآن وليس غداً، فهذه اللحظة في يدي ولكن غداً في يد الله. أحد الآباء');
INSERT INTO fathers_quotes (author, quote) VALUES ('القديسين', 'لا تخاصم إنسان فربما لا تعيش حتى تصالحه. أحد الآباء');
INSERT INTO fathers_quotes (author, quote) VALUES ('أحد الشيوخ', 'من الزم السكون ينجو من سهام العدو.');
INSERT INTO fathers_quotes (author, quote) VALUES ('أحد الشيوخ', 'طوبى لمن أبصر خطاياه كل حين.');
INSERT INTO fathers_quotes (author, quote) VALUES ('الأنباأنطونيوس', 'إذ أردت أن تخلص، ففر من شيطان العظمة واجعل لك قليل بكاء.');
