import type { Config } from "tailwindcss";
import forms from "@tailwindcss/forms";

const config: Config = {
  theme: {
    extend: {
      colors: {
        outline: "#897172",
        "inverse-surface": "#303030",
        "on-surface-variant": "#564243",
        "secondary-fixed": "#ffe088",
        "on-surface": "#1b1b1c",
        "on-primary-fixed-variant": "#822334",
        "on-secondary-fixed-variant": "#574500",
        tertiary: "#20211f",
        "on-primary-container": "#f27987",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#c7c7c3",
        "surface-container-low": "#f6f3f2",
        "outline-variant": "#dcc0c1",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#fed65b",
        "on-secondary-container": "#745c00",
        "on-tertiary-container": "#9f9f9b",
        "on-primary-fixed": "#40000f",
        "on-error": "#ffffff",
        "inverse-primary": "#ffb2b8",
        "surface-tint": "#a13b4a",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#e3e2df",
        "on-tertiary-fixed-variant": "#464744",
        "on-secondary-fixed": "#241a00",
        "surface-variant": "#e5e2e1",
        "on-tertiary-fixed": "#1b1c1a",
        "tertiary-container": "#353634",
        surface: "#fcf9f8",
        secondary: "#735c00",
        "primary-fixed-dim": "#ffb2b8",
        "secondary-fixed-dim": "#e9c349",
        primary: "#4a0012",
        "on-error-container": "#93000a",
        "surface-container-high": "#eae7e7",
        "surface-container-highest": "#e5e2e1",
        error: "#ba1a1a",
        "on-primary": "#ffffff",
        "on-background": "#1b1b1c",
        background: "#fcf9f8",
        "surface-container": "#f0eded",
        "primary-container": "#6b1124",
        "primary-fixed": "#ffdadb",
        "surface-dim": "#dcd9d9",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#f3f0ef",
        "surface-bright": "#fcf9f8",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        lg: "48px",
        sm: "12px",
        base: "8px",
        "max-width": "1200px",
        xl: "80px",
        "margin-mobile": "16px",
        "margin-desktop": "auto",
        md: "24px",
        gutter: "20px",
        xs: "4px",
      },
      fontFamily: {
        "label-sm": ["Plus Jakarta Sans"],
        "display-lg-mobile": ["Libre Caslon Text"],
        "headline-md-mobile": ["Libre Caslon Text"],
        "display-lg": ["Libre Caslon Text"],
        "body-lg": ["Plus Jakarta Sans"],
        "headline-md": ["Libre Caslon Text"],
        "title-lg": ["Libre Caslon Text"],
        "body-md": ["Plus Jakarta Sans"],
      },
      fontSize: {
        "label-sm": [
          "12px",
          { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "display-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-md-mobile": [
          "24px",
          { lineHeight: "1.3", fontWeight: "600" },
        ],
        "display-lg": [
          "48px",
          { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "title-lg": ["22px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
      },
    },
  },
};
