import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Abona Faltaos</title>
        <meta name="description" content="Chritian things like: Tranim, Al7an, W3zat and 3geda" />
        <meta name="author" content="Peter Eshak Abdo" />
        <Link href="https://cdn.jsdelivr.net/npm/@docsearch/css@3" rel="stylesheet" />
        {/* <Script src="../src/js/bootstrap/color-modes.js"></Script>
        <Link href="../src/css/bootstrap/main.css" rel="stylesheet" />
        <Link href="../src/css/bootstrap/bootstrap.rtl.min.css" rel="stylesheet" /> */}
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.3/css/bootstrap.rtl.min.css"
          integrity="sha512-VNBisELNHh6+nfDjsFXDA6WgXEZm8cfTEcMtfOZdx0XTRoRbr/6Eqb2BjqxF4sNFzdvGIt+WqxKgn0DSfh2kcA=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
        {/* <Script
          src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.3/js/bootstrap.min.js"
          integrity="sha512-ykZ1QQr0Jy/4ZkvKuqWn4iF3lqPZyij9iRv6sGqLRdTPkY69YX6+7wvVGmsdBbiIfN/8OdsI7HABjvEok6ZopQ=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        ></Script> */}
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>{children}</body>
      <Script
        src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.3/js/bootstrap.bundle.min.js"
        integrity="sha512-7Pi/otdlbbCR+LnW+F7PwFcSDJOuUJB3OxtEHbg4vSMvzvJjde4Po1v4BR9Gdc9aXNUNFVUY+SK51wWT8WF0Gg=="
        crossOrigin="anonymous"
        referrerPolicy="no-referrer"
      ></Script>
    </html>
  );
}
export default RootLayout;







