import "./globals.css";
import Link from "next/link";
import Script from "next/script";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
function serviceWorker () {
  if ("serviceWorker" in navigator) {
    window.addEventListener("load", async () => {
      try {
        const registration = await navigator.serviceWorker.register("sw.js");
        console.log("Service worker registered for scope", registration.scope);
      } catch (err) {
          if (err instanceof Error) {
          console.error(err.name, err.message);
        } else {
          console.error(err);
        }
      }
    });
  }
  }
function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Register the service worker as a side effect
  serviceWorker();
  return (
    <html lang="ar" dir="rtl">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>ابونا فلتاؤس السرياني</title>
        <meta
          name="description"
          content="الحان وترانيم ووعظات او عظات وكتب ومقالات ومواقع مسيحية وكل ما يخص الكنيسة السريانية الارثوذكسية"
        />
        <meta name="author" content="بيتر اسحاق عبده" />
        <Link
          href="https://cdn.jsdelivr.net/npm/@docsearch/css@3"
          rel="stylesheet"
        />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.3/css/bootstrap.rtl.min.css"
          integrity="sha512-VNBisELNHh6+nfDjsFXDA6WgXEZm8cfTEcMtfOZdx0XTRoRbr/6Eqb2BjqxF4sNFzdvGIt+WqxKgn0DSfh2kcA=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        {/* <Script
          src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.3/js/bootstrap.min.js"
          integrity="sha512-ykZ1QQr0Jy/4ZkvKuqWn4iF3lqPZyij9iRv6sGqLRdTPkY69YX6+7wvVGmsdBbiIfN/8OdsI7HABjvEok6ZopQ=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        ></Script> */}
        {/* Service worker registration is handled outside JSX */}
        <link rel="manifest" id="manifest-placeholder" href="./manifest.webmanifest"/>
        {serviceWorker()}
      </head>
      <body >
        {children}
      </body>
      <Script
        src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.3/js/bootstrap.bundle.min.js"
        integrity="sha512-7Pi/otdlbbCR+LnW+F7PwFcSDJOuUJB3OxtEHbg4vSMvzvJjde4Po1v4BR9Gdc9aXNUNFVUY+SK51wWT8WF0Gg=="
        crossOrigin="anonymous"
        referrerPolicy="no-referrer"
      ></Script>
    </html>
  );
}
export default RootLayout;
